"use strict";
exports.__esModule = true;
var herancapessoa_1 = require("./herancapessoa");
var herancaaluno_1 = require("./herancaaluno");
var herancaprofessor_1 = require("./herancaprofessor");
var p;
p = new herancapessoa_1.Pessoa();
p.setNumRegistro(1234);
p.setNome("Genereites de Albuquerque Lima Filho Jr");
p.setEmail("gene@generates.com.br");
p.setTelefone("+55 11 98765-4321");
console.log(p);
var a;
a = new herancaaluno_1.Aluno();
a.setNumRegistro(1235);
a.setNome("Isidro de Almeida Botelho");
a.setEmail("isi@isidrocorp.com");
a.setTelefone("+55 11 12345-6789");
a.setCurso("Java Full Stack Galaxy Master");
a.setAnoMatricula(2019);
console.log(a);
var pro;
pro = new herancaprofessor_1.Professor();
pro.setNumRegistro(1236);
pro.setNome("Miguel Antonio");
pro.setEmail("professor@chique.com");
pro.setTelefone("+55 11 12345-6789");
pro.setvalorHora(100);
pro.setnumHoras(250);
pro.setareaFormacao("linguistica");
console.log(pro);
